DROP TABLE IF EXISTS form;
DROP TABLE IF EXISTS form_alternative;
DROP TABLE IF EXISTS form_data;

CREATE TABLE form (form_id INTEGER PRIMARY KEY, created TEXT NOT NULL, id TEXT KEY NOT NULL, name TEXT KEY NOT NULL, datakey TEXT NOT NULL, data TEXT NOT NULL, errors TEXT NOT NULL, status INTEGER KEY NOT NULL DEFAULT 0);
CREATE TABLE form_alternative (form_id INTEGER PRIMARY KEY, created TEXT NOT NULL, id TEXT KEY NOT NULL, name TEXT KEY NOT NULL, datakey TEXT NOT NULL, data TEXT NOT NULL, errors TEXT NOT NULL, status INTEGER KEY NOT NULL DEFAULT 0);

CREATE TABLE form_data (form_id INTEGER PRIMARY KEY, created TEXT NOT NULL, id TEXT KEY NOT NULL, name TEXT KEY NOT NULL, datakey TEXT NOT NULL, data TEXT NOT NULL, errors TEXT NOT NULL, status INTEGER KEY NOT NULL DEFAULT 0);

BEGIN TRANSACTION;
INSERT INTO "form_data" VALUES(1,'2010-10-17 05:35:41','form1','article','','{"title":"The title of the \"article\" goes here - 80","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 48","created":"2010-10-17 05:35:41","views":778}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(2,'2010-10-17 05:35:41','form2','article','','{"title":"The title of the \"article\" goes here - 32","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 63","created":"2010-10-17 05:35:41","views":491}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(3,'2010-10-17 05:35:41','form3','article','','{"title":"The title of the \"article\" goes here - 31","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 46","created":"2010-10-17 05:35:41","views":809}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(4,'2010-10-17 05:35:41','form4','article','','{"title":"The title of the \"article\" goes here - 49","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 56","created":"2010-10-17 05:35:41","views":383}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(5,'2010-10-17 05:35:41','form5','article','','{"title":"The title of the \"article\" goes here - 91","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 76","created":"2010-10-17 05:35:41","views":592}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(6,'2010-10-17 05:35:41','form6','article','','{"title":"The title of the \"article\" goes here - 21","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 2","created":"2010-10-17 05:35:41","views":712}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(7,'2010-10-17 05:35:41','form7','article','','{"title":"The title of the \"article\" goes here - 57","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 99","created":"2010-10-17 05:35:41","views":799}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(8,'2010-10-17 05:35:41','form8','article','','{"title":"The title of the \"article\" goes here - 83","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 2","created":"2010-10-17 05:35:41","views":12}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(9,'2010-10-17 05:35:41','form9','article','','{"title":"The title of the \"article\" goes here - 32","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 32","created":"2010-10-17 05:35:41","views":552}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(10,'2010-10-17 05:35:41','form10','article','','{"title":"The title of the \"article\" goes here - 34","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 98","created":"2010-10-17 05:35:41","views":177}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(11,'2010-10-17 05:35:41','form11','article','','{"title":"The title of the \"article\" goes here - 64","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 81","created":"2010-10-17 05:35:41","views":675}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(12,'2010-10-17 05:35:41','form12','article','','{"title":"The title of the \"article\" goes here - 63","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 13","created":"2010-10-17 05:35:41","views":815}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(13,'2010-10-17 05:35:41','form13','article','','{"title":"The title of the \"article\" goes here - 32","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 69","created":"2010-10-17 05:35:41","views":358}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(14,'2010-10-17 05:35:41','form14','article','','{"title":"The title of the \"article\" goes here - 4","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 40","created":"2010-10-17 05:35:41","views":148}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(15,'2010-10-17 05:35:41','form15','article','','{"title":"The title of the \"article\" goes here - 3","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 47","created":"2010-10-17 05:35:41","views":937}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(16,'2010-10-17 05:35:41','form16','article','','{"title":"The title of the \"article\" goes here - 68","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 40","created":"2010-10-17 05:35:41","views":215}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(17,'2010-10-17 05:35:41','form17','article','','{"title":"The title of the \"article\" goes here - 33","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 21","created":"2010-10-17 05:35:41","views":567}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(18,'2010-10-17 05:35:41','form18','article','','{"title":"The title of the \"article\" goes here - 88","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 3","created":"2010-10-17 05:35:41","views":211}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(19,'2010-10-17 05:35:41','form19','article','','{"title":"The title of the \"article\" goes here - 84","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 36","created":"2010-10-17 05:35:41","views":589}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
INSERT INTO "form_data" VALUES(20,'2010-10-17 05:35:41','form20','article','','{"title":"The title of the \"article\" goes here - 1","content":"Article''s are just about the ''coolest!'' thing you can wrote content is here - 88","created":"2010-10-17 05:35:41","views":480}','{"title":"The field title can not be empty","content":"The field content must have 20 characters or more"}',1);
COMMIT;